### ISSUE TITLE
Afriso Plug

### ISSUE THREAD

**Issue by sbloecks** [Jey-Cee/ioBroker.enocean#158] opened 2022-11-10 17:34 UTC
**Manufacturer**:Afriso
**Model**:APR234
**Production date/period**:2021
**Link to product**:https://www.afriso.com/ix_pim_assets/PDF/4/84/584/900_000_0752.PDF

**Comment by Jey-Cee** [comment] 2022-11-13 07:57
Please don't waste my time and check the next time if your device wasn't requested already.
Duplicate of #156

**Closed as completed by Jey-Cee** 2022-11-13 07:57 UTC
Labels: Device request
